# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07eb2f26339d3a1bd9f8cbc531dcdf2c5eed42b09f9c2c9f47e056738a1c21af5e86b923b00fea0bec133b3d064c4ae9bb1910a503dd7fbf8cb7db8cfdefe7ae

test:
  secret_key_base: 1f90ab6132f45c8d2fb48fc3c4ccc667cf7a57ac5f97bcbf68f6607cccee8c7aa6a9844b3370a7745098a11d627b046e57003de409da7b6d25923bce06b2efff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
